apiVersion: v2
name: stardog-az
description: Helm chart to deploy Stardog Cluster and associated services
version: 2.0.5
appVersion: latest
home: https://marlonabarua.github.io/stardog-helm/
icon: https://s3.amazonaws.com/stardog-logos.public/stardog-logo.png
maintainers:
  - name: Stardog Union
    email: tech@stardog.com
    url: https://www.stardog.com
dependencies:
  - name: zookeeper
    version: 6.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: zookeeper.enabled
